{{- if .Values.rgwExporter.secret.values }}
---

apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Values.rgwExporter.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $k, $v := .Values.rgwExporter.secret.values }}
    {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
