---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9198
      protocol: TCP
      targetPort: http-metrics
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
